package main

import (
	"log"
	"warung-online/api"
	_ "warung-online/docs" // docs is generated by Swag CLI, you have to import it.
	"warung-online/internal/logger"
	"warung-online/internal/repository"
	"warung-online/internal/usecase"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Warung Online API
// @version 1.0
// @description This is a sample server for a warung online.
// @host localhost:8080
// @BasePath /
func main() {
	appLogger := logger.NewLogger()

	db, err := repository.NewSQLiteDB("warung.db")
	if err != nil {
		appLogger.Fatalf("failed to connect to database: %v", err)
	}

	if err := repository.InitDB(db); err != nil {
		appLogger.Fatalf("failed to initialize database: %v", err)
	}

	// Initialize repositories
	orderRepo := repository.NewSQLiteOrderRepository(db, appLogger)
	stockRepo := repository.NewSQLiteStockRepository(db, appLogger)

	// Initialize usecases
	orderUsecase := usecase.NewOrderUsecase(orderRepo, stockRepo, appLogger)
	stockUsecase := usecase.NewStockUsecase(stockRepo, appLogger)

	// Initialize handlers
	orderHandler := api.NewOrderHandler(orderUsecase)
	stockHandler := api.NewStockHandler(stockUsecase)

	// Initialize router
	router := api.NewRouter(orderHandler, stockHandler)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	log.Println("Server running at :8080")
	router.Run(":8080")
}
